aPackageInfo = [
	:name = "The VisualStudioEditorExtension Package",
	:description = "Our VisualStudioEditorExtension package using the Ring programming language",
	:folder = "visualstudioeditorextension",
	:developer = "Mahmoud Fayed",
	:email = "msfclipper@yahoo.com",
	:license = "MIT License",
	:version = "1.0.0",
	:ringversion = "1.10",
	:versions = 	[
		[
			:version = "1.0.0",
			:branch = "master"
		]
	],
	:libs = 	[
		[
			:name = "",
			:version = "",
			:providerusername = ""
		]
	],
	:files = 	[
		"main.ring",
		"README.md"
	],
	:ringfolderfiles = 	[
		"editor/visualstudio/.vs/RingForVS/v15/.suo",
		"editor/visualstudio/MPFProj12/BuildProcessTemplates/DefaultTemplate.xaml",
		"editor/visualstudio/MPFProj12/BuildProcessTemplates/LabDefaultTemplate.xaml",
		"editor/visualstudio/MPFProj12/BuildProcessTemplates/UpgradeTemplate.xaml",
		"editor/visualstudio/MPFProj12/DesignDocuments/Checking the projectfile for security.docx",
		"editor/visualstudio/MPFProj12/DesignDocuments/Global property handling.docx",
		"editor/visualstudio/MPFProj12/DesignDocuments/Microsoft.VisualStudio.Project.tmd",
		"editor/visualstudio/MPFProj12/DesignDocuments/Project - diagrams.vsd",
		"editor/visualstudio/MPFProj12/DesignDocuments/Project Designer support.doc",
		"editor/visualstudio/MPFProj12/Dev12/Microsoft.VisualStudio.Project.IntegrationTests.testrunconfig",
		"editor/visualstudio/MPFProj12/Dev12/Microsoft.VisualStudio.Project.sln",
		"editor/visualstudio/MPFProj12/Dev12/Microsoft.VisualStudio.Project.Tests.sln",
		"editor/visualstudio/MPFProj12/Dev12/Microsoft.VisualStudio.Project.UnitTests.testrunconfig",
		"editor/visualstudio/MPFProj12/Dev12/Microsoft.VisualStudio.Project.v11.suo",
		"editor/visualstudio/MPFProj12/Dev12/Microsoft.VisualStudio.Project.v12.suo",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/CustomProject.sln",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/CustomProject.UnitTests.sln",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/LocalTestRun.testrunconfig",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/Attributes/LocDisplayNameAttribute.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/Attributes/ResourcesCategoryAttribute.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/Attributes/ResourcesDescriptionAttribute.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/CustomProject.csproj",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/CustomProjectPackage.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/extension.vsixmanifest",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/GeneralPropertyPage.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/GlobalSuppressions.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/GuidStrings.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/Key.snk",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/MyCustomProjectAutomation.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/MyCustomProjectFactory.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/MyCustomProjectFileNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/MyCustomProjectNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/Properties/AssemblyInfo.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/Resources/MyCustomProjectImageList.bmp",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/Resources.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/Resources.resx",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/source.extension.vsixmanifest",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/Templates/ProjectItems/MyCustomProject/Class.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/Templates/Projects/MyCustomProject/AssemblyInfo.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/Templates/Projects/MyCustomProject/MyCustomProject.ico",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/Templates/Projects/MyCustomProject/MyCustomProject.myproj",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/Templates/Projects/MyCustomProject/Program.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/Src/VSPackage.resx",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/BaseTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/CustomProject.UnitTests.csproj",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/GeneralPropertyPageTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/Mocks/MockILocalRegistry.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/Mocks/MockIVsFileChangeEx.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/Mocks/MockIVsRegisterProjectTypes.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/Mocks/MockIVsShell.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/Mocks/MockIVsSolution.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/Mocks/MockIVsSolutionBuildManager.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/Mocks/MockIVsTaskList.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/Mocks/MockIVsUIShell.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/MyCustomFileNodeTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/MyCustomProjectFactoryTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/MyCustomProjectNodeTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/PackageTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/Properties/AssemblyInfo.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/Templates/AssemblyInfo.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/Templates/MyCustomProject.ico",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/Templates/MyCustomProject.myproj",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/CustomProject/UnitTests/Templates/Program.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/localtestrun.testrunconfig",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/NestedProject.sln",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/NestedProject.UnitTests.sln",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/Attributes/LocDisplayNameAttribute.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/Attributes/ResourcesCategoryAttribute.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/Attributes/ResourcesDescriptionAttribute.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/Automation/OANestedProject.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/Automation/OANestedProjectProperties.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/Automation/OANestedProjectProperty.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/ConfigurationPropertyPages.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/extension.vsixmanifest",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/GeneralPropertyPage.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/GeneralPropertyPageTag.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/GuidStrings.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/NestedProject.csproj",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/NestedProjectFactory.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/NestedProjectNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/NestedProjectPackage.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/Properties/AssemblyInfo.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/Resources.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/Resources.resx",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/source.extension.vsixmanifest",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/Templates/ProjectItems/Class.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/Templates/Projects/Application.nestedproj",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/Templates/Projects/AssemblyInfo.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/Src/Templates/Projects/Program.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/UnitTests/AttributesTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/UnitTests/AutomationTests.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/UnitTests/BaseTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/UnitTests/GeneralPropertyPageTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/UnitTests/MockServicesProvider.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/UnitTests/NestedProject.UnitTests.csproj",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/UnitTests/NestedProjectFactoryTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/UnitTests/NestedProjectNodeTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/UnitTests/NestedProjectPackageTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/UnitTests/Properties/AssemblyInfo.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/UnitTests/Templates/SampleClass.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/UnitTests/Templates/SampleProject.csproj",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/UnitTests/Templates/TemplateClass.cs",
		"editor/visualstudio/MPFProj12/Dev12/Samples/CSharp/NestedProject/UnitTests/VSCodeGenAccessors.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/AssemblyReferenceNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Attributes.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/AutomationScope.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/OAFileItem.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/OAFolderItem.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/OANavigableProjectItems.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/OANestedProjectItem.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/OANullProperty.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/OAProject.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/OAProjectItem.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/OAProjectItems.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/OAProperties.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/OAProperty.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/OAReferenceFolderItem.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/OAReferenceItem.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/OASolutionFolder.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/VSProject/OAAssemblyReference.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/VSProject/OABuildManager.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/VSProject/OAComReference.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/VSProject/OAProjectReference.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/VSProject/OAReferenceBase.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/VSProject/OAReferences.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/VSProject/OAVSProject.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Automation/VSProject/OAVSProjectItem.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/BuildDependency.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/BuildPropertyPage.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ComReferenceNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ConfigProvider.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ConfigurationProperties.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/DataObject.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/DependentFileNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/DesignPropertyDescriptor.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/DesignTimeAssemblyResolution.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Diagrams/AutomationClasses.cd",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Diagrams/ConfigurationClasses.cd",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Diagrams/DocumentManagerClasses.cd",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Diagrams/HierarchyClasses.cd",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Diagrams/PropertiesClasses.cd",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Diagrams/ReferenceClasses.cd",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/DocumentManager.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/EnumDependencies.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/FileChangeManager.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/FileDocumentManager.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/FileNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/FolderNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/GlobalSuppressions.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/HierarchyNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/IDEBuildLogger.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ImageHandler.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Interfaces.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Key.snk",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/LocalizableProperties.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Microsoft.VisualStudio.Project.csproj",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Misc/ConnectionPointContainer.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Misc/ExternDll.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Misc/NativeMethods.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Misc/UnsafeNativeMethods.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/MPFProjectAll.files",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/NestedProjectBuildDependency.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/NestedProjectNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/NodeProperties.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/obj/Debug/TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/obj/Debug/TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/obj/Debug/TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/OleServiceProvider.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Output.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/OutputGroup.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ProjectBase.files",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ProjectConfig.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ProjectContainerNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ProjectDesignerDocumentManager.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ProjectDocumentsListener.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ProjectElement.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ProjectFactory.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ProjectFileConstants.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ProjectNode.CopyPaste.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ProjectNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ProjectNode.Events.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ProjectOptions.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ProjectPackage.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ProjectReferenceNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Properties/AssemblyInfo.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/PropertiesEditorLauncher.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ReferenceContainerNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/ReferenceNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/RegisteredProjectType.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Resources/imagelis.bmp",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/SelectionListener.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/SettingsPage.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/SingleFileGenerator.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/SingleFileGeneratorFactory.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/SolutionListener.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/SolutionListenerForBuildDependencyUpdate.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/SolutionListenerForProjectEvents.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/SolutionListenerForProjectOpen.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/SolutionListenerForProjectReferenceUpdate.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/StructuresEnums.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/SuspendFileChanges.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/TokenProcessor.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Tracing.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/TrackDocumentsHelper.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/TypeConverters.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/UIThread.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/UpdateSolutionEventsListener.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Url.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/Utilities.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/VisualStudio.Project.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/VisualStudio.Project.resx",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/VsCommands.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/VSShellUtilities.cs",
		"editor/visualstudio/MPFProj12/Dev12/Src/CSharp/WebProjectBase.Files",
		"editor/visualstudio/MPFProj12/Dev12/Tests/IntegrationTests/BaseTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/IntegrationTests/DialogboxPurger.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/IntegrationTests/Microsoft.VisualStudio.Project.IntegrationTests.csproj",
		"editor/visualstudio/MPFProj12/Dev12/Tests/IntegrationTests/NativeMethods.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/IntegrationTests/Project.nestedproj",
		"editor/visualstudio/MPFProj12/Dev12/Tests/IntegrationTests/Properties/AssemblyInfo.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/IntegrationTests/TestAutomation.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/IntegrationTests/TestGlobalProperties.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/IntegrationTests/TestNode.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/IntegrationTests/TestProject.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/IntegrationTests/Utilities.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/BuildLoggerTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/ImageHandlerTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/Microsoft.VisualStudio.Project.UnitTests.csproj",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/MockFactories.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/ProjectEventsTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/ProjectTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/ProjectTestClass.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/Properties/AssemblyInfo.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/Properties/Resources.Designer.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/Properties/Resources.resx",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/Resources/Image1.bmp",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/Resources/ImageList.bmp",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/TestDirectory.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/TestProject.proj",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/TokenProcessorTest.cs",
		"editor/visualstudio/MPFProj12/Dev12/Tests/UnitTests/Utilities.cs",
		"editor/visualstudio/MPFProj12/Documentation/General Notes Including new IVsBuildManagerAccessor.docx",
		"editor/visualstudio/MPFProj12/Documentation/MPF Proj documentation.docx",
		"editor/visualstudio/README.md",
		"editor/visualstudio/Ring.VisualStudio.Editor/Properties/AssemblyInfo.cs",
		"editor/visualstudio/Ring.VisualStudio.Editor/Ring.VisualStudio.Editor.csproj",
		"editor/visualstudio/Ring.VisualStudio.Editor/RingLanguage.cs",
		"editor/visualstudio/Ring.VisualStudio.Editor/RingSyntax.cs",
		"editor/visualstudio/Ring.VisualStudio.Editor/RingSyntaxFormat.cs",
		"editor/visualstudio/Ring.VisualStudio.Editor/RingSyntaxType.cs",
		"editor/visualstudio/Ring.VisualStudio.Editor/source.extension.vsixmanifest",
		"editor/visualstudio/RingForVS.sln",
		"editor/visualstudio/RingVSIX/GeneralPropertyPage.cs",
		"editor/visualstudio/RingVSIX/GlobalSuppressions.cs",
		"editor/visualstudio/RingVSIX/Guids.cs",
		"editor/visualstudio/RingVSIX/ItemTemplates/Ring/Class/Definitions/CSharp.vstemplate",
		"editor/visualstudio/RingVSIX/ItemTemplates/Ring/Class/icon.png",
		"editor/visualstudio/RingVSIX/ItemTemplates/Ring/Class/readme.txt",
		"editor/visualstudio/RingVSIX/ItemTemplates/Ring/Definitions/CSharp.vstemplate",
		"editor/visualstudio/RingVSIX/ItemTemplates/Ring/Item/NewFile.ring",
		"editor/visualstudio/RingVSIX/ItemTemplates/Ring/ringlogo.jpg",
		"editor/visualstudio/RingVSIX/Key.snk",
		"editor/visualstudio/RingVSIX/packages.config",
		"editor/visualstudio/RingVSIX/Properties/AssemblyInfo.cs",
		"editor/visualstudio/RingVSIX/Properties/template-builder.props",
		"editor/visualstudio/RingVSIX/Resources/Package.ico",
		"editor/visualstudio/RingVSIX/Resources/RingNode.bmp",
		"editor/visualstudio/RingVSIX/Resources.Designer.cs",
		"editor/visualstudio/RingVSIX/Resources.resx",
		"editor/visualstudio/RingVSIX/RingForVS.bat",
		"editor/visualstudio/RingVSIX/RingGuidList.cs",
		"editor/visualstudio/RingVSIX/RingProjectFactory.cs",
		"editor/visualstudio/RingVSIX/RingProjectNode.cs",
		"editor/visualstudio/RingVSIX/RingProjectPackage.cs",
		"editor/visualstudio/RingVSIX/RingVSIX.csproj",
		"editor/visualstudio/RingVSIX/Screenshot_4.png",
		"editor/visualstudio/RingVSIX/source.extension.vsixmanifest",
		"editor/visualstudio/RingVSIX/Templates/Projects/Ring/CSharp.vstemplate",
		"editor/visualstudio/RingVSIX/Templates/Projects/Ring/NewFile1.ring",
		"editor/visualstudio/RingVSIX/Templates/Projects/Ring/RingProject.ico",
		"editor/visualstudio/RingVSIX/Templates/Projects/Ring/RingProject.ringproj",
		"editor/visualstudio/RingVSIX/thering.jpg",
		"editor/visualstudio/RingVSIX/VSPackage.resx",
		"editor/visualstudio/RingVSIX.vsix",
		"editor/visualstudio/UpgradeLog.htm"
	],
	:windowsfiles = 	[

	],
	:linuxfiles = 	[

	],
	:macosfiles = 	[

	],
	:windowsringfolderfiles = 	[

	],
	:linuxringfolderfiles = 	[

	],
	:macosringfolderfiles = 	[

	],
	:run = "ring main.ring",
	:setup = "",
	:windowssetup = "",
	:linuxsetup = "",
	:macossetup = "",
	:ubuntusetup = "",
	:fedorasetup = "",
	:remove = "",
	:windowsremove = "",
	:linuxremove = "",
	:macosremove = "",
	:ubunturemove = "",
	:fedoraremove = ""
]